# Generated by Django 4.2.7 on 2023-12-03 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assign',
            options={'verbose_name': 'Associação', 'verbose_name_plural': 'Associações'},
        ),
        migrations.AlterModelOptions(
            name='frequenciaturma',
            options={'verbose_name': 'Frequência', 'verbose_name_plural': 'Frequências'},
        ),
    ]
